name = "tunnel"
main = "src/index.js"
compatibility_date = "2024-01-01"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"
# TROJAN_PASSWORD = "your-trojan-password"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
